# Web App - Customer Website Deployment
[build]
  command = "./build-web-app.sh"
  publish = "apps/web-app/dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  # Production environment variables
  NODE_ENV = "production"
  REACT_APP_ENV = "production"
  # Disable automatic dependency installation
  NPM_FLAGS = "--legacy-peer-deps"
  
[context.production]
  command = "./build-web-app.sh"

[context.staging]
  command = "./build-web-app.sh"
  
# Development server for Netlify Dev
[dev]
  command = "npx nx serve @mycompany/web-app"
  port = 4200
  targetPort = 4200

# Asset optimization
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
