[build]
  command = "nx build @mycompany/web-app"
  publish = "apps/web-app/dist"

[build.environment]
  NODE_VERSION = "22"
  NPM_VERSION = "10"

[dev]
  command = "nx serve @mycompany/web-app"
  port = 4201

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
